export const indianCities: string[] = [
  "Adilabad", "Agar Malwa", "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola", "Alappuzha",
  "Aligarh", "Alipurduar", "Alirajpur", "Alluri Sitharama Raju", "Almora", "Alwar", "Ambala", "Ambedkar Nagar",
  "Amethi", "Amravati", "Amreli", "Amritsar", "Amroha", "Anakapalli", "Anand", "Ananthapuramu", "Anantnag",
  "Angul", "Anjaw", "Annamayya", "Anuppur", "Anupgarh", "Araria", "Aravalli", "Arwal", "Ashoknagar", "Auraiya",
  "Aurangabad", "Ayodhya", "Azamgarh", "Badaun", "Bagalkot", "Bageshwar", "Baghpat", "Bahraich", "Bajali",
  "Baksa", "Balaghat", "Balangir", "Balod", "Baloda Bazar", "Balotra", "Balrampur", "Balsore", "Banda",
  "Banaskantha", "Banka", "Bankura", "Banswara", "Bapatla", "Barabanki", "Baramulla", "Baran", "Bareilly",
  "Bargarh", "Barmer", "Barnala", "Barpeta", "Barwani", "Bastar", "Basti", "Bathinda", "Beawar", "Beed",
  "Begusarai", "Belagavi", "Bemetara", "Bengaluru Rural", "Bengaluru Urban", "Betul", "Bhadohi", "Bhagalpur",
  "Bhadrak", "Bhadradri Kothagudem", "Bharatpur", "Bharuch", "Bhavnagar", "Bhilwara", "Bhind", "Bhiwani",
  "Bhojpur", "Bhopal", "Bidar", "Bijapur", "Bijnor", "Bikaner", "Bilaspur", "Birbhum", "Bishnupur", "Biswanath",
  "Bokaro", "Bongaigaon", "Botad", "Boudh", "Budgam", "Bulandshahr", "Buldhana", "Bundi", "Burhanpur", "Buxar",
  "Cachar", "Central Delhi", "Chamarajanagar", "Chamba", "Chamoli", "Champawat", "Champhai", "Chandauli",
  "Chandel", "Chandigarh", "Chandrapur", "Changlang", "Charaideo", "Charkhi Dadri", "Chatra", "Chengalpattu",
  "Chennai", "Chhota Udaipur", "Chhindwara", "Chikkaballapura", "Chikkamagaluru", "Chirang", "Chitradurga",
  "Chitrakoot", "Chittoor", "Chümoukedima", "Churu", "Churachandpur", "Coimbatore", "Cooch Behar", "Cuddalore",
  "Cuttack", "Dadra and Nagar Haveli", "Dahod", "Dakshin Dinajpur", "Dakshina Kannada", "Daman", "Damoh",
  "Dang", "Dantewada", "Darbhanga", "Darjeeling", "Darrang", "Datia", "Dausa", "Davangere", "Debagarh", "Deeg",
  "Dehradun", "Deoghar", "Deoria", "Devbhoomi Dwarka", "Dewas", "Dhalai", "Dhamtari", "Dhanbad", "Dhar",
  "Dharmapuri", "Dharwad", "Dhemaji", "Dholpur", "Dhubri", "Dhule", "Dibang Valley", "Dibrugarh",
  "Didwana-Kuchaman", "Dima Hasao", "Dimapur", "Dindigul", "Dindori", "Diu", "Doda", "Dr. B.R. Ambedkar Konaseema",
  "Dumka", "Dungarpur", "Durg", "East Champaran", "East Delhi", "East Garo Hills", "East Godavari",
  "East Jaintia Hills", "East Kameng", "East Khasi Hills", "East Siang", "East Singhbhum", "Eastern West Khasi Hills",
  "Eluru", "Ernakulam", "Erode", "Etah", "Etawah", "Faridabad", "Farrukhabad", "Fatehabad", "Fatehgarh Sahib",
  "Fatehpur", "Fazilka", "Firozabad", "Ferozepur", "Gadag", "Gadchiroli", "Gajapati", "Ganderbal", "Gandhinagar",
  "Ganganagar", "Gangtok", "Ganjam", "Garhwa", "Gariyaband", "Gautam Buddha Nagar", "Gaurela Pendra Marwahi",
  "Gaya", "Ghaziabad", "Ghazipur", "Gir Somnath", "Giridih", "Goa Velha", "Goalpara", "Godda", "Golaghat",
  "Gomati", "Gonda", "Gondia", "Gopalganj", "Gorakhpur", "Gumla", "Guntur", "Gurdaspur", "Gurugram", "Gwalior",
  "Gyalshing", "Hailakandi", "Hamirpur", "Hanumakonda", "Hanumangarh", "Hapur", "Harda", "Hardoi", "Haridwar",
  "Hassan", "Hathras", "Haveri", "Hingoli", "Hisar", "Hnahthial", "Hojai", "Hooghly", "Hoshangabad", "Hoshiarpur",
  "Howrah", "Hyderabad", "Idukki", "Imphal East", "Imphal West", "Indore", "Jabalpur", "Jagatsinghpur",
  "Jagtial", "Jaipur", "Jaipur Rural", "Jajapur", "Jaisalmer", "Jalandhar", "Jalaun", "Jalgaon", "Jalna",
  "Jalore", "Jammu", "Jamnagar", "Jamtara", "Jamui", "Jangaon", "Janjgir-Champa", "Jashpur", "Jaunpur",
  "Jayashankar Bhupalpally", "Jehanabad", "Jhajjar", "Jhalawar", "Jhansi", "Jhargram", "Jharsuguda", "Jhunjhunu",
  "Jind", "Jiribam", "Jodhpur", "Jodhpur Rural", "Jogulamba Gadwal", "Jorhat", "Junagadh", "Kabirdham",
  "Kachchh", "Kaimur", "Kaithal", "Kakinada", "Kakching", "Kalaburagi", "Kalahandi", "Kalimpong", "Kallakurichi",
  "Kamareddy", "Kamjong", "Kamle", "Kamrup", "Kamrup Metropolitan", "Kanchipuram", "Kandhamal", "Kangra",
  "Kangpokpi", "Kanker", "Kannauj", "Kannur", "Kanpur Dehat", "Kanpur Nagar", "Kanyakumari", "Kapurthala",
  "Karaikal", "Karauli", "Karbi Anglong", "Kargil", "Karimganj", "Karimnagar", "Karnal", "Karur", "Kasaragod",
  "Kasganj", "Kathua", "Katihar", "Katni", "Kaushambi", "Kekri", "Kendrapara", "Kendujhar", "Khagaria",
  "Khairthal-Tijara", "Khammam", "Khandwa", "Khargone", "Khawzawl", "Kheri", "Khordha", "Khowai", "Khunti",
  "Kinnaur", "Kiphire", "Kishanganj", "Kishtwar", "Kodagu", "Koderma", "Kohima", "Kolar", "Kolasib", "Kolkata",
  "Kollam", "Kondagaon", "Koppal", "Koraput", "Korba", "Koriya", "Kota", "Kotputli-Behror", "Kottayam",
  "Kozhikode", "Kra Daadi", "Krishna", "Krishnagiri", "Kulgam", "Kullu", "Kumuram Bheem Asifabad", "Kupwara",
  "Kurnool", "Kurukshetra", "Kurung Kumey", "Kushinagar", "Lahaul and Spiti", "Lakhimpur", "Lakhisarai",
  "Lakshadweep", "Lalitpur", "Latur", "Lawngtlai", "Leh", "Lepa Rada", "Lohardaga", "Lohit", "Longding",
  "Longleng", "Lucknow", "Ludhiana", "Lunglei", "Madhepura", "Madhubani", "Madurai", "Mahabubabad",
  "Mahabubnagar", "Maharajganj", "Mahasamund", "Mahe", "Mahendragarh", "Mahesana", "Mahisagar", "Mahoba",
  "Mainpuri", "Majuli", "Malappuram", "Malda", "Malkangiri", "Mamit", "Mancherial", "Mandla", "Mandsaur",
  "Mandya", "Mangan", "Manipur", "Mansa", "Mathura", "Mau", "Mayiladuthurai", "Mayurbhanj", "Medak",
  "Medchal-Malkajgiri", "Meerut", "Mirzapur", "Moga", "Mokokchung", "Mon", "Moradabad", "Morbi", "Morigaon",
  "Muktsar", "Mulugu", "Mumbai City", "Mumbai Suburban", "Munger", "Mungeli", "Murshidabad", "Muzaffarnagar",
  "Muzaffarpur", "Mysuru", "Nabarangpur", "Nadia", "Nagaon", "Nagapattinam", "Nagarkurnool", "Nagaur",
  "Nagpur", "Nainital", "Nalanda", "Nalgonda", "Nalbari", "Namakkal", "Namchi", "Namsai", "Nanded",
  "Nandurbar", "Nandyal", "Narayanpet", "Narayanpur", "Narmada", "Narsinghpur", "Nashik", "Navsari",
  "Nawada", "Nayagarh", "Neem Ka Thana", "Neemuch", "New Delhi", "Nicobars", "Nilgiris", "Nirmal", "Nizamabad",
  "Noklak", "Noney", "North 24 Parganas", "North Delhi", "North East Delhi", "North Garo Hills", "North Goa",
  "North and Middle Andaman", "North Tripura", "North West Delhi", "NTR", "Nuh", "Nuapada", "Osmanabad",
  "Pakke Kessang", "Pakur", "Pakyong", "Palakkad", "Palamu", "Palghar", "Pali", "Palnadu", "Palwal",
  "Panchkula", "Panchmahal", "Panipat", "Panna", "Papum Pare", "Parbhani", "Parvathipuram Manyam",
  "Paschim Bardhaman", "Paschim Medinipur", "Patan", "Pathanamthitta", "Pathankot", "Patiala", "Patna",
  "Pauri Garhwal", "Peddapalli", "Perambalur", "Peren", "Pherzawl", "Phalodi", "Phek", "Pilibhit",
  "Pithoragarh", "Poonch", "Porbandar", "Prakasam", "Pratapgarh", "Prayagraj", "Puducherry", "Pudukkottai",
  "Pulwama", "Pune", "Purba Bardhaman", "Purba Medinipur", "Puri", "Purnia", "Purulia", "Raebareli",
  "Raigarh", "Raigad", "Raipur", "Raisen", "Rajanna Sircilla", "Rajgarh", "Rajkot", "Rajnandgaon", "Rajouri",
  "Rajsamand", "Ramanagara", "Ramanathapuram", "Ramban", "Ramgarh", "Rampur", "Ranchi", "Ranga Reddy",
  "Ranipet", "Ratlam", "Ratnagiri", "Rayagada", "Reasi", "Rewa", "Rewari", "Ri Bhoi", "Rohtas", "Rohtak",
  "Rudraprayag", "Rupnagar", "Sabarkantha", "Sagar", "Saharanpur", "Sahibganj", "Sahibzada Ajit Singh Nagar",
  "Shahid Bhagat Singh Nagar", "Saharsa", "Saiha", "Saitual", "Salem", "Salumbar", "Samba", "Sambalpur",
  "Sambhal", "Samastipur", "Sanchore", "Sangareddy", "Sangli", "Sangrur", "Sant Kabir Nagar", "Saran",
  "Satara", "Satna", "Sawai Madhopur", "Sehore", "Senapati", "Seoni", "Seraikela Kharsawan", "Serchhip",
  "Shahdara", "Shahdol", "Shajapur", "Shahpura", "Shamator", "Shamli", "Sheikhpura", "Sheohar", "Sheopur",
  "Shi Yomi", "Shivamogga", "Shivpuri", "Shopian", "Siddharthnagar", "Siddipet", "Sidhi", "Sikar", "Siang",
  "Simdega", "Sindhudurg", "Singrauli", "Sirmaur", "Sirohi", "Sirsa", "Sitamarhi", "Sitapur", "Sivasagar",
  "Siwan", "Solan", "Solapur", "Sonbhadra", "Sonipat", "Sonitpur", "Soreng", "South 24 Parganas", "South Andaman",
  "South Delhi", "South East Delhi", "South West Delhi", "South Garo Hills", "South Goa", "South West Garo Hills",
  "South West Khasi Hills", "South Salmara-Mankachar", "South Tripura", "Sri Ganganagar", "Sri Muktsar Sahib",
  "Sri Potti Sriramulu Nellore", "Sri Sathya Sai", "Srikakulam", "Srinagar", "Sukma", "Sultanpur", "Sundergarh",
  "Supaul", "Surajpur", "Surat", "Surendranagar", "Surguja", "Suryapet", "Tamenglong", "Tamil Nadu", "Tapi",
  "Tarn Taran", "Tawang", "Tehri Garhwal", "Tenkasi", "Tengnoupal", "Thane", "Thanjavur", "Theni", "Thiruvananthapuram",
  "Thoothukudi", "Thoubal", "Thrissur", "Tikamgarh", "Tinsukia", "Tirap", "Tiruchirappalli", "Tirunelveli",
  "Tirupattur", "Tirupati", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur", "Tonk", "Tripura",
  "Tseminyü", "Tuensang", "Tumakuru", "Udaipur", "Udalguri", "Udham Singh Nagar", "Udupi", "Ujjain",
  "Ukhrul", "Umaria", "Unakoti", "Una", "Unnao", "Upper Siang", "Upper Subansiri", "Uttar Dinajpur",
  "Uttarkashi", "Vadodara", "Vaishali", "Valsad", "Varanasi", "Vellore", "Vidisha", "Vijayapura", "Vijayanagara",
  "Vikarabad", "Viluppuram", "Virudhunagar", "Visakhapatnam", "Vizianagaram", "Wanaparthy", "Warangal",
  "Wardha", "Washim", "Wayanad", "West Champaran", "West Delhi", "West Garo Hills", "West Godavari",
  "West Jaintia Hills", "West Kameng", "West Karbi Anglong", "West Khasi Hills", "West Siang", "West Singhbhum",
  "West Tripura", "Wokha", "Yadadri Bhuvanagiri", "Yadgir", "Yanam", "Yavatmal", "YSR Kadapa", "Zunheboto",
  "Ambur", "Arakkonam", "Arani", "Aruppukkottai", "Attur", "Avadi", "Bhavani", "Bodinayakanur",
  "Chengalpattu", "Chennai", "Chidambaram", "Coimbatore", "Coonoor", "Courtallam", "Cuddalore",
  "Cumbum", "Darasuram", "Devakottai", "Dhanushkodi", "Dharapuram", "Dharmapuri", "Dindigul",
  "Erode", "Gangaikonda Cholapuram", "Gingee", "Gobichettipalayam", "Gudalur", "Gudiyatham",
  "Hosur", "Kallakurichi", "Kanchipuram", "Kanyakumari", "Karaikudi", "Karur", "Kodaikanal",
  "Kotagiri", "Kovilpatti", "Krishnagiri", "Kumbakonam", "Madurai", "Mahabalipuram", "Mannargudi",
  "Mayiladuthurai", "Meghamalai", "Mettupalayam", "Nagapattinam", "Nagercoil", "Namakkal",
  "Neyveli", "Ooty", "Palani", "Palladam", "Paramakudi", "Pattukkottai", "Perambalur",
  "Pollachi", "Pudukkottai", "Rajapalayam", "Rameswaram", "Ranipet", "Salem", "Sirkazhi",
  "Sivaganga", "Sivakasi", "Srirangam", "Srivilliputhur", "Tambaram", "Tenkasi", "Thanjavur",
  "Theni", "Thiruthani", "Thiruvallur", "Thiruvarur", "Thoothukudi", "Tindivanam", "Tiruchendur",
  "Tiruchengode", "Tiruchirappalli", "Tirunelveli", "Tirupattur", "Tiruppur", "Tiruttani",
  "Tiruvannamalai", "Tranquebar", "Udhagamandalam", "Valparai", "Vaniyambadi", "Varanasi",
  "Velankanni", "Vellore", "Viluppuram", "Virudhachalam", "Virudhunagar", "Yercaud", "Yelagiri"
];

