/**
 * install-hooks.cjs
 * Run once to install the Git pre-commit hook:
 *   node scripts/install-hooks.cjs
 *
 * The hook will automatically backup the Appwrite database before any commit
 * that touches backend-related files (scripts/, .env, appwrite.json, etc.)
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const GIT_HOOKS_DIR = path.join(PROJECT_ROOT, '.git', 'hooks');
const HOOK_PATH = path.join(GIT_HOOKS_DIR, 'pre-commit');

const HOOK_CONTENT = `#!/bin/sh
# ============================================================
# AUTO-GENERATED by scripts/install-hooks.cjs
# Truck Trip Tracker — Appwrite Auto-Backup Pre-Commit Hook
#
# Runs an Appwrite database backup before any commit that
# touches backend-critical files. Aborts the commit if
# the backup fails (prevents accidental data loss).
# ============================================================

# Files/directories that trigger the backup
BACKEND_PATTERNS="scripts/ .env appwrite.json"

# Check if any staged file matches backend patterns
SHOULD_BACKUP=0
for pattern in $BACKEND_PATTERNS; do
  if git diff --cached --name-only | grep -q "^$pattern"; then
    SHOULD_BACKUP=1
    break
  fi
done

if [ "$SHOULD_BACKUP" = "1" ]; then
  echo ""
  echo "==========================================================="
  echo "⚠  Backend files detected in this commit."
  echo "⚠  Running Appwrite database backup before proceeding..."
  echo "==========================================================="
  echo ""

  node scripts/backup-db.cjs
  BACKUP_EXIT=$?

  if [ $BACKUP_EXIT -ne 0 ]; then
    echo ""
    echo "❌ COMMIT ABORTED: Database backup failed!"
    echo "   Fix the backup issue before committing backend changes."
    echo "   (Check VITE_APPWRITE_API_KEY is set in your .env file)"
    echo ""
    exit 1
  fi

  echo ""
  echo "✅ Backup successful — proceeding with commit."
  echo ""
fi

exit 0
`;

function installHook() {
  // Verify .git directory exists
  if (!fs.existsSync(GIT_HOOKS_DIR)) {
    console.error('❌ .git/hooks directory not found. Are you in the project root?');
    console.error(`   Expected: ${GIT_HOOKS_DIR}`);
    process.exit(1);
  }

  // Write the hook file
  fs.writeFileSync(HOOK_PATH, HOOK_CONTENT, { encoding: 'utf8', mode: 0o755 });

  // On Windows, Git hooks don't need chmod but set it anyway for WSL/cross-platform
  try {
    fs.chmodSync(HOOK_PATH, 0o755);
  } catch (e) {
    // chmod may fail on Windows — that's fine, Git for Windows handles this
  }

  console.log('');
  console.log('✅ Git pre-commit hook installed successfully!');
  console.log(`   Location: ${HOOK_PATH}`);
  console.log('');
  console.log('How it works:');
  console.log('  • Every commit touching scripts/, .env, or appwrite.json');
  console.log('    will automatically back up the Appwrite DB first.');
  console.log('  • If the backup fails, the commit is BLOCKED.');
  console.log('  • Backups are saved to: <project>/backups/');
  console.log('  • Backups are in .gitignore — never pushed to GitHub.');
  console.log('');
}

installHook();
